name: CI
on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia test
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2  
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1

  docs:
    name: Documentation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@latest

